export const enum DmgTypes {
	/** 蒸发 */
	vaporize = 'vaporize',
	/** 融化 */
	melt = 'melt',
	/** 燃烧 */
	burning = 'burning',
	/** 结晶 */
	crystallize = 'crystallize',
	/** 超导 */
	superConduct = 'superConduct',
	/** 感电 */
	electroCharged = 'electroCharged',
	/** 超载 */
	overloaded = 'overloaded',
	/** 扩散 */
	swirl = 'swirl',
	/** 碎冰 */
	shatter = 'shatter',
	/** 物理伤害 */
	phy = 'phy',
	/** 绽放 */
	bloom = 'bloom',
	/** 烈绽放 */
	burgeon = 'burgeon',
	/** 超绽放 */
	hyperBloom = 'hyperBloom',
	/** 超激化 */
	aggravate = 'aggravate',
	/** 蔓激化 */
	spread = 'spread',
}